### ISSUE TITLE
Adapt iframe height when contacting MJ

### ISSUE THREAD

**Issue by T4m** [orcidee/rpgconmanager#1]
As user I want to see the contact form without annoying scrolling, when I click on contact form in the parties list.

**Hint**
- Call JS method adaptIframeHeight
- Do it from the rpgconmanager

**Comment by Dansimati** [comment]
Or change the form, and make it open in a lightbox ---> easier for Joomla to set the iframe height.

**Comment by T4m** [comment]
I added the height adaptation but didn't change the form. Because now, the form is available only in the party's detailed page, (not anymore in the list).
