### ISSUE TITLE
DB doesn't take modification into account

### ISSUE THREAD

**Issue by Dansimati** [orcidee/rpgconmanager#27]
When admin (animator too?) modifies party, DB doesn't register it.

**Comment by Dansimati** [comment]
<p class="dbg">You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`tableAmount`='1' WHERE `partyId` = '80'' at line 1</p>

**Comment by Dansimati** [comment]
J'ai réussi à régler de manière provisoire le problème en supprimant la ligne 166 de classes/party.php:
 "`tableAmount`='".addslashes($this->tableAmount)."'".
Ça veut dire que les gens ne peuvent plus mettre à jour le nb de tables souhaitées, mais c'est rarement ça qu'ils veulent mettre à jour, donc en attendant que quelqu'un s'y colle, je vais faire comme ça.

**Comment by Dansimati** [comment]
Quand on arrive sur la feuille pour éditer, l'heure se remet au choix par défaut... donc 11h le premier jour.

**Comment by T4m** [comment]
Fixed

**Comment by T4m** [comment]
I reopen for hour

**Comment by T4m** [comment]
Fixed
