### ISSUE TITLE
Correct 2nd and 3rd tables in Assignation des tables

### ISSUE THREAD

**Issue by Dansimati** [orcidee/rpgconmanager#35]
In a party second and third fields in Assignation des tables, we find:
<br /><b>Notice</b>:  Undefined offset: 1 in <b>/home/www/f569f31f94be128cd394b39f165b9157/web/orcidee/manager/pages/tables.php</b> on line <b>79</b><br />

**Comment by T4m** [comment]
Je vois plus ou moins où c'est, mais je n'arrive pas à reproduire. Dans quel cas ça survient ?

**Comment by Dansimati** [comment]
![capture_tables](https://cloud.githubusercontent.com/assets/2010500/12574224/368afbae-c402-11e5-9df8-7233a0a56feb.jpg)
Ici...

**Comment by T4m** [comment]
ça j'ai vu, merci. Ma question c'est comment ça vient ? J'arrive pas à reproduire. ça arrive tout le temps chez toi ?

**Comment by T4m** [comment]
Fixed
