### ISSUE TITLE
Show tables amount in party list

### ISSUE THREAD

**Issue by Dansimati** [orcidee/rpgconmanager#37]
All in the title

**Comment by T4m** [comment]
Je comprends pas le titre. Le nombre de table dans la liste des partie... pourquoi ? Tu veux dire le numéro de table ?

**Comment by T4m** [comment]
Si tu parle du numéro de table, il y a déjà #12

**Comment by Dansimati** [comment]
le nombre de table demandée par la partie...

**Comment by T4m** [comment]
Le nombre de table demandée est actuellement affiché dans la liste et le détail.
