### ISSUE TITLE
Supprimer l'envoi du mail de confirmation à moduleparties

### ISSUE THREAD

**Issue by Dansimati** [orcidee/rpgconmanager#40]
Actuellement, moduleparties reçoit à la fois une copie de la confirmation envoyée au joueur et une copie du mail envoyer au mj. Ne garder que le mail envoyé au mj.

**Comment by T4m** [comment]
Pour l'instant, il y a 8 mails possiblement envoyé. Avec chacun une copie moduleparties. Dis moi exactement auxquels tu veux enlever le CC : 
- sendPassword
- notifyCancel
- notifyVerify
- notifyValidate
- notifyRefuse
- notifySubscribtion
- notifyUnsubscribtion
- subscribeToParty
- unsubscribeToParty
- unsubscribedToParty
- ctcAdmin
- unsubscribedToCanceledParty
- notifyCreate

**Comment by Dansimati** [comment]
Dans le cas des inscriptions joueurs, je reçois la version joueur et la version MJ... je pense que tu peux supprimer la copie du mail envoyé au joueur à modulepartie.
Et plus généralement le problème, c'est que je reçois deux mails par actions. Je ne sais pas d'où ça vient, mais ça encombre singulièrement ma boître mail. Je reçois tout ce que reçoit "modulepartie", donc visiblement, il y a un soucis quelque part... Chaque fois que je valide une partie, bim, deux mails... le même,  à double.
