### ISSUE TITLE
Error  Undefined index

### ISSUE THREAD

**Issue by Dansimati** [orcidee/rpgconmanager#52]
La liste des parties affiche:
 Notice: Undefined index: partyState in /home/www/f569f31f94be128cd394b39f165b9157/web/orcidee/manager/pages/list.php on line 116

**Comment by Dansimati** [comment]
Et quand on est pas connecté, on a ça sur la page liste des parties:
Fatal error: Call to a member function isAdmin() on a non-object in /home/www/f569f31f94be128cd394b39f165b9157/web/orcidee/manager/pages/list.php on line 199

**Comment by Dansimati** [comment]
Pour le premier, j'ai réussi à préciser: c'est quand on ne choisit un pas état de partie que ce message s'affiche

**Comment by T4m** [comment]
C'est fixé, en tout cas, je n'arrive pas à reproduire. :-)
